'use client'

import './globals.css'
import React, {useState} from 'react'
import { useRouter } from 'next/navigation';
import type { Metadata } from 'next'

// Import Components 
import SidebarButton from './components/sidebar/SidebarButton';
import SidebarButtonDropdown from './components/sidebar/SidebarButtonDropdown';

// import icons 
import { IconContext } from "react-icons";
import { TiDocumentDelete } from 'react-icons/ti'
import { BsClipboardCheck } from 'react-icons/bs';
import { GiAutoRepair } from 'react-icons/gi'
// overview icons 
import { MdStart } from 'react-icons/md';
import { ImStatsDots } from 'react-icons/im';
import { AiOutlineRead } from 'react-icons/ai';
// agile icons 
import { MdOutlineManageAccounts } from 'react-icons/md';
import { MdOutlineDashboard } from 'react-icons/md';
import { BsCardChecklist } from 'react-icons/bs';
import { LiaTasksSolid } from 'react-icons/lia';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Sidebar Btn Dropdown  
  const [overviewDropDown,   setOverviewDropDown]   = useState(false);
  const [agileDropDown,      setAgileDropDown]      = useState(false);
  const [automationDropDown, setAutomationDropDown] = useState(false);
  const [pipelineDropDown,   setPipelineDropDown]   = useState(false);
  const [otherDropDown,      setOtherDropDown]      = useState(false);

  const dropDownNames = ["Overview", "Agile", "Automation"]; // TODO: add other dropdown btns 
  const dropDownSetters = [setOverviewDropDown, setAgileDropDown, setAutomationDropDown, setPipelineDropDown, setOtherDropDown]; 

  // set dropdown icons 
  const overviewIcons = [MdStart, ImStatsDots, AiOutlineRead];
  const agileIcons    = [MdOutlineManageAccounts, MdOutlineDashboard, 
                         BsCardChecklist, LiaTasksSolid];

  const { push } = useRouter();

  // Setup Homebtn
  const handleTitleBtnReroute = (e : any) => {
    e.preventDefault(); 
    push('/');
  } 

  return (
    <html lang="en">
      <body>
        <div id="topbar-container">
                <div id="title-container">
                    <button id = "title-btn" onClick={handleTitleBtnReroute}><b>AutoDevOps</b></button> 
                </div>
        </div>
        <div id='sidebar-container'>
          <SidebarButton name="Overview" dropDownState = {overviewDropDown} 
                    dropDownNames={dropDownNames} dropDownSetters={dropDownSetters} 
                    inputIcon={TiDocumentDelete}/>
          <SidebarButtonDropdown name="Overview" dropdownVisibile={overviewDropDown} 
                                 dropdownIcons={overviewIcons}/>

          <SidebarButton name="Agile" dropDownState = {agileDropDown} 
                    dropDownNames={dropDownNames} dropDownSetters={dropDownSetters} 
                    inputIcon={BsClipboardCheck}/>
          <SidebarButtonDropdown name="Agile" dropdownVisibile={agileDropDown} 
                                 dropdownIcons={agileIcons}/>

          {/* <SidebarButton name="Automation" dropDownState = {automationDropDown} 
                    dropDownNames={dropDownNames} dropDownSetters={dropDownSetters} 
                    inputIcon={GiAutoRepair}/>
          <SidebarButtonDropdown name="Agile" dropdownVisibile={automationDropDown} /> */}
        </div>

        <div className='content-container'>
          {children} 
        </div>
      </body>
    </html>
  )
}
