'use client'

import './globals.css'
import React, {useState} from 'react'
import { useRouter } from 'next/navigation';
import type { Metadata } from 'next'

// Import Components 
import SidebarButton from './components/sidebar/SidebarButton';
import SidebarButtonDropdown from './components/sidebar/SidebarButtonDropdown';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Sidebar Btn Dropdown  
  const [overviewDropDown, setOverviewDropDown] = useState(false);
  const [agileDropDown,    setAgileDropDown]    = useState(false);
  const [pipelineDropDown, setPipelineDropDown] = useState(false);
  const [otherDropDown,    setOtherDropDown]    = useState(false);

  const dropDownNames = ["Overview", "Agile"]; // TODO: add other dropdown btns 
  const dropDownSetters = [setOverviewDropDown, setAgileDropDown, setPipelineDropDown, setOtherDropDown]; 

  const { push } = useRouter();

  // Setup Homebtn
  const handleTitleBtnReroute = (e : any) => {
    e.preventDefault(); 
    push('/');
  } 

  return (
    <html lang="en">
      <body>
        <div id="topbar-container">
                <div id="title-container">
                    <button id = "title-btn" onClick={handleTitleBtnReroute}><b>AutoDevOps</b></button> 
                </div>
        </div>
      
        <div id='sidebar-container'>
          <SidebarButton name="Overview" dropDownState = {overviewDropDown} dropDownNames={dropDownNames} dropDownSetters={dropDownSetters} />
          <SidebarButtonDropdown name="Overview" dropdownVisibile={overviewDropDown} />

          <SidebarButton name="Agile" dropDownState = {agileDropDown} dropDownNames={dropDownNames} dropDownSetters={dropDownSetters} />
          <SidebarButtonDropdown name="Agile" dropdownVisibile={agileDropDown} />
        </div>

        <div className='content-container'>
          {children} 
        </div>
      </body>
    </html>
  )
}
